spring:
  application:
    name: ecommerce_api

  docker:
    compose:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        query:
          fail_on_pagination_over_collection_fetch: true

  data:
    web:
      pageable:
        serialization-mode: via-dto

app:
  errors:
    include-details: false

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

logging:
  level:
    root: INFO
