package alexo.ecommerce_api.configuration.openapi;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.media.*;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import org.springdoc.core.customizers.GlobalOpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Aligns generated OpenAPI schemas with the runtime API envelope.
 * Ensures Swagger reflects the actual JSON emitted by controller methods.
 */
@Configuration
public class OpenApiConfig {

    /**
     * Wraps JSON responses in the standard envelope and fixes documented success status codes.
     *
     * @return global OpenAPI customizer
     */
    @Bean
    public GlobalOpenApiCustomizer standardApiSchemaCustomizer() {
        return this::customizeOpenApi;
    }

    /**
     * Applies schema adjustments to generated OpenAPI components and operation responses.
     *
     * @param openApi mutable OpenAPI document generated by springdoc
     */
    private void customizeOpenApi(OpenAPI openApi) {
        if (openApi.getPaths() == null) {
            return;
        }

        openApi.getPaths().forEach((path, pathItem) -> {
            if (pathItem == null || pathItem.readOperationsMap() == null) {
                return;
            }

            pathItem.readOperationsMap().forEach((method, operation) -> {
                alignSuccessStatus(path, method, operation);

                if (operation.getResponses() == null) {
                    return;
                }
                operation.getResponses().values().forEach(this::wrapJsonResponse);
            });
        });
    }

    /**
     * Replaces JSON response schemas with the standardized API envelope schema.
     *
     * @param apiResponse operation response definition to mutate
     */
    private void wrapJsonResponse(ApiResponse apiResponse) {
        Content content = apiResponse.getContent();
        if (content == null) {
            return;
        }

        content.forEach((mediaTypeName, mediaType) -> {
            if (!isJsonLike(mediaTypeName) || mediaType.getSchema() == null) {
                return;
            }

            Schema<?> originalSchema = mediaType.getSchema();
            if (isAlreadyWrapped(originalSchema)) {
                return;
            }

            ObjectSchema wrapperSchema = new ObjectSchema();
            wrapperSchema.addProperty("payload", originalSchema);
            wrapperSchema.addProperty("date", new DateTimeSchema());
            ComposedSchema errorsSchema = new ComposedSchema();
            errorsSchema.setOneOf(List.of(
                    new ArraySchema().items(new StringSchema()),
                    new ObjectSchema()
            ));
            wrapperSchema.addProperty("errors", errorsSchema);
            wrapperSchema.setRequired(List.of("date"));
            mediaType.setSchema(wrapperSchema);
        });
    }

    /**
     * Detects whether a response schema is already described as the API envelope.
     *
     * @param schema response schema to inspect
     * @return {@code true} when the schema already contains envelope fields
     */
    private boolean isAlreadyWrapped(Schema<?> schema) {
        if (schema == null) {
            return false;
        }

        if (schema.get$ref() != null && schema.get$ref().contains("ApiResponseDTO")) {
            return true;
        }

        if (schema.getProperties() == null) {
            return false;
        }

        return schema.getProperties().containsKey("payload")
                && schema.getProperties().containsKey("date")
                && schema.getProperties().containsKey("errors");
    }

    /**
     * Aligns success status code in docs with runtime status returned by endpoints.
     *
     * @param path OpenAPI path
     * @param method HTTP method
     * @param operation operation to mutate
     */
    private void alignSuccessStatus(String path, PathItem.HttpMethod method, Operation operation) {
        if (operation == null || operation.getResponses() == null || method == null) {
            return;
        }

        ApiResponses responses = operation.getResponses();
        boolean shouldUseCreated = isCreatedEndpoint(path, method);

        if (shouldUseCreated) {
            moveSuccessResponseCode(responses, "200", "201");
            return;
        }

        moveSuccessResponseCode(responses, "201", "200");
    }

    /**
     * Returns true for endpoints that intentionally return HTTP 201 Created.
     */
    private boolean isCreatedEndpoint(String path, PathItem.HttpMethod method) {
        if (method != PathItem.HttpMethod.POST) {
            return false;
        }

        return "/api/auth/signup".equals(path)
                || "/api/catalog/category".equals(path)
                || "/api/catalog/product".equals(path);
    }

    private void moveSuccessResponseCode(ApiResponses responses, String fromCode, String toCode) {
        if (responses.containsKey(toCode)) {
            return;
        }
        if (!responses.containsKey(fromCode)) {
            return;
        }

        ApiResponse moved = responses.remove(fromCode);
        responses.addApiResponse(toCode, moved);
    }

    /**
     * Matches media types that should expose the standardized JSON response envelope.
     *
     * @param mediaTypeName OpenAPI media type key
     * @return {@code true} for JSON and wildcard response media types
     */
    private boolean isJsonLike(String mediaTypeName) {
        return org.springframework.http.MediaType.APPLICATION_JSON_VALUE.equals(mediaTypeName)
                || mediaTypeName.endsWith("+json")
                || org.springframework.http.MediaType.ALL_VALUE.equals(mediaTypeName);
    }
}