package alexo.ecommerce_api.configuration.openapi;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.*;
import io.swagger.v3.oas.models.responses.ApiResponse;
import org.springdoc.core.customizers.GlobalOpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Aligns generated OpenAPI schemas with the runtime API envelope and `$type` metadata.
 * Ensures Swagger reflects the actual JSON emitted by the global response wrapper.
 */
@Configuration
public class OpenApiConfig {

    /**
     * Adds `$type` to object schemas and wraps JSON responses in the standard envelope.
     *
     * @return global OpenAPI customizer
     */
    @Bean
    public GlobalOpenApiCustomizer standardApiSchemaCustomizer() {
        return this::customizeOpenApi;
    }

    /**
     * Applies schema adjustments to generated OpenAPI components and operation responses.
     *
     * @param openApi mutable OpenAPI document generated by springdoc
     */
    private void customizeOpenApi(OpenAPI openApi) {
        Components components = openApi.getComponents();
        if (components != null && components.getSchemas() != null) {
            components.getSchemas().forEach(this::addTypeProperty);
        }

        if (openApi.getPaths() == null) {
            return;
        }

        openApi.getPaths().values().forEach(pathItem -> pathItem.readOperations().forEach(operation -> {
            if (operation.getResponses() == null) {
                return;
            }

            operation.getResponses().values().forEach(this::wrapJsonResponse);
        }));
    }

    /**
     * Adds the `$type` discriminator field to object-like component schemas.
     *
     * @param schemaName component schema name used as `$type` example
     * @param schema generated schema to enrich
     */
    private void addTypeProperty(String schemaName, Schema<?> schema) {
        if (schema == null || !isObjectLike(schema)) {
            return;
        }

        Map<String, Schema> properties = schema.getProperties();
        if (properties == null) {
            properties = new LinkedHashMap<>();
            schema.setProperties(properties);
        }

        properties.putIfAbsent("$type", new StringSchema().example(schemaName));

        List<String> required = schema.getRequired();
        if (required == null) {
            required = new ArrayList<>();
            schema.setRequired(required);
        }
        if (!required.contains("$type")) {
            required.add("$type");
        }
    }

    /**
     * Replaces JSON response schemas with the standardized API envelope schema.
     *
     * @param apiResponse operation response definition to mutate
     */
    private void wrapJsonResponse(ApiResponse apiResponse) {
        Content content = apiResponse.getContent();
        if (content == null) {
            return;
        }

        content.forEach((mediaTypeName, mediaType) -> {
            if (!isJsonLike(mediaTypeName) || mediaType.getSchema() == null) {
                return;
            }

            Schema<?> originalSchema = mediaType.getSchema();
            if (isAlreadyWrapped(originalSchema)) {
                return;
            }

            ObjectSchema wrapperSchema = new ObjectSchema();
            wrapperSchema.addProperty("$type", new StringSchema().example("ApiResponse"));
            wrapperSchema.addProperty("payload", originalSchema);
            wrapperSchema.addProperty("date", new DateTimeSchema());
            wrapperSchema.addProperty("errors", new ArraySchema().items(new StringSchema()));
            wrapperSchema.setRequired(List.of("$type", "date"));
            mediaType.setSchema(wrapperSchema);
        });
    }

    /**
     * Detects whether a response schema is already described as the API envelope.
     *
     * @param schema response schema to inspect
     * @return {@code true} when the schema already contains envelope fields
     */
    private boolean isAlreadyWrapped(Schema<?> schema) {
        if (schema == null || schema.getProperties() == null) {
            return false;
        }

        return schema.getProperties().containsKey("payload")
                && schema.getProperties().containsKey("date")
                && schema.getProperties().containsKey("$type");
    }

    /**
     * Determines whether a schema can safely receive an injected `$type` property.
     *
     * @param schema schema to classify
     * @return {@code true} for object-like and composed schemas
     */
    private boolean isObjectLike(Schema<?> schema) {
        if (schema instanceof ComposedSchema) {
            return true;
        }

        if (schema.getAdditionalProperties() != null) {
            return true;
        }

        return "object".equals(schema.getType()) || schema.getProperties() != null;
    }

    /**
     * Matches media types that should expose the standardized JSON response envelope.
     *
     * @param mediaTypeName OpenAPI media type key
     * @return {@code true} for JSON and wildcard response media types
     */
    private boolean isJsonLike(String mediaTypeName) {
        return org.springframework.http.MediaType.APPLICATION_JSON_VALUE.equals(mediaTypeName)
                || mediaTypeName.endsWith("+json")
                || org.springframework.http.MediaType.ALL_VALUE.equals(mediaTypeName);
    }
}